-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "crowdfunding_platform"."pledge" add column "status" text
--  not null default 'pending';
