-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "crowdfunding_platform"."campaign" add column "end_status" text
--  not null default 'pending';
