-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "crowdfunding_platform"."campaign_report" add column "created_at" timestamptz
--  null default now();
