-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "crowdfunding_platform"."voucher" add column "value" numeric
--  not null default '50';
