version: '3.6'
services:
  crowdfunding_db:
    container_name: crowdfunding_db
    image: postgres:12
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}