version: '3.6'
services:
  crowdfunding_db:
    container_name: crowdfunding_db
    image: postgres:13-alpine
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    networks:
      - main
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

networks:
  main:
    driver: bridge