-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "crowdfunding_platform"."project" add column "creator_id" uuid
--  not null;
